### ISSUE TITLE
ModuleNotFoundError: No module named 'django.contrib.gisproperty'

### ISSUE THREAD

**Issue by SamNgu** [Pythondeveloper6/Build-Hotel-Site-With-Python-Django#3]
After installation, and pip install -r requirements inside venv, got this error..

**Comment by SamNgu** [comment]
Found the problem, the source code setting file missing a ',' after the 'django.contrib.gis'.

**Comment by itsvinayak** [comment]
Check the entry in your INSTALLED_APPS :

`'django.contrib.gis', `

this should be there if not place it

**Comment by itsvinayak** [comment]
there was a missing ',' in code, fixed in [PR](https://github.com/Pythondeveloper6/Build-Hotel-Site-With-Python-Django/pull/5)

**Comment by noobprogrammer27** [comment]
how can i overcome the error no module named 'django.contrib.gisproperty'

**Comment by itsvinayak** [comment]
Just place a ',' in settings.py look pr

**Comment by itsvinayak** [comment]
> how can i overcome the error no module named 'django.contrib.gisproperty'

Check the entry in your INSTALLED_APPS :

'django.contrib.gis',

this should be there if not place it

in this Just place a ',' in settings.py look [PR](https://github.com/Pythondeveloper6/Build-Hotel-Site-With-Python-Django/pull/5)

**Comment by Eng-MostafaAllam** [comment]
Hi bro I added this lien but it doesn't work.

**Comment by weilihua1** [comment]
感谢你提出的解决方法 找了一个下午no module named 'django.contrib.gisproperty'
